services:
  Aws\Credentials\Credentials:
    autowire: true
    arguments:
      $key: '%aws.accessKeyId%'
      $secret: '%aws.secretAccessKey%'

  Aws\S3\S3Client:
    autowire: true
    factory: ['Gsu\SyllabusPortal\ThirdParty\AWS\S3ClientFactory', 'create']
