SELECT
  SSBSECT_TERM_CODE AS "termCode",
  STVTERM_DESC as "termName",
  SSBSECT_CRN AS "crn",
  STVCOLL_CODE AS "collegeCode",
  STVCOLL_DESC AS "collegeName",
  STVDEPT_CODE AS "departmentCode",
  STVDEPT_DESC AS "departmentName",
  STVCAMP_CODE AS "campusCode",
  STVCAMP_DESC AS "campusName",
  SCBCRSE_EFF_TERM AS "courseEffectiveTerm",
  SSBSECT_SUBJ_CODE  AS "subjectCode",
  SSBSECT_CRSE_NUMB AS "courseNumber",
  SSBSECT_SEQ_NUMB AS "courseSequence",
  NVL(SSBSECT_CRSE_TITLE,SCBCRSE_TITLE) AS "courseTitle",
  NVL(SIRASGN_PIDM,'0') AS "instructorPidm",
  NVL(SPRIDEN_ID,'STAFF') AS "instructorId",
  SPRIDEN_FIRST_NAME AS "instructorFirstName",
  SPRIDEN_LAST_NAME AS "instructorLastName",
  GOREMAL_EMAIL_ADDRESS AS "instructorEmail"
FROM
  SSBSECT@BREPTS,
  SCBCRSE@BREPTS,
  SSBOVRR@BREPTS,
  SIRASGN@BREPTS,
  SPRIDEN@BREPTS,
  GOREMAL@BREPTS,
  STVTERM@BREPTS,
  STVCOLL@BREPTS,
  STVDEPT@BREPTS,
  (
    SELECT
      STVCAMP_CODE AS BANNER_CAMP_CODE,
      CASE
        WHEN STVCAMP_CODE IN ('PF','ON','OG') THEN 'ON'
        WHEN STVCAMP_CODE IN ('PA','PC','PE','PN','PS') THEN 'PER'
        WHEN STVCAMP_CODE IN ('A','1') THEN 'ATL'
        WHEN STVCAMP_CODE IN ('I') THEN 'FOR'
        WHEN STVCAMP_CODE IN ('X','F','PF') THEN 'OFF'
        ELSE 'OTH'
      END AS STVCAMP_CODE,
      CASE
        WHEN STVCAMP_CODE IN ('PF','ON','OG') THEN 'Online Campus'
        WHEN STVCAMP_CODE IN ('PA','PC','PE','PN','PS') THEN 'Perimeter Campus'
        WHEN STVCAMP_CODE IN ('A','1') THEN 'Atlanta Campus'
        WHEN STVCAMP_CODE IN ('I') THEN 'Foreign Campus'
        WHEN STVCAMP_CODE IN ('X','F','PF') THEN 'Off-campus'
        ELSE 'Other USG Institution'
      END AS STVCAMP_DESC
    FROM
      STVCAMP@BREPTS
  ) STVCAMP
WHERE
  -- SSBSECT
  SSBSECT_TERM_CODE = :termCode AND
  SSBSECT_SSTS_CODE = 'A' AND
  SSBSECT_INTG_CDE IS NULL AND
  -- SCBCRSE
  SCBCRSE_SUBJ_CODE = SSBSECT_SUBJ_CODE AND
  SCBCRSE_CRSE_NUMB = SSBSECT_CRSE_NUMB AND
  SCBCRSE_CSTA_CODE = 'A' AND
  SCBCRSE_EFF_TERM = (
    SELECT
      MAX(i.SCBCRSE_EFF_TERM)
    FROM
      SCBCRSE@BREPTS i
    WHERE
      i.SCBCRSE_SUBJ_CODE = SSBSECT_SUBJ_CODE AND
      i.SCBCRSE_CRSE_NUMB = SSBSECT_CRSE_NUMB AND
      i.SCBCRSE_EFF_TERM <= SSBSECT_TERM_CODE AND
      i.SCBCRSE_CSTA_CODE = 'A'
  ) AND
  -- SSBOVRR
  SSBOVRR_TERM_CODE(+) = SSBSECT_TERM_CODE AND
  SSBOVRR_CRN(+) = SSBSECT_CRN AND
  -- SIRASGN
  SIRASGN_TERM_CODE(+) = SSBSECT_TERM_CODE AND
  SIRASGN_CRN(+) = SSBSECT_CRN AND
  SIRASGN_PRIMARY_IND(+) = 'Y' AND
  -- SPRIDEN
  SPRIDEN_PIDM(+) = SIRASGN_PIDM AND
  SPRIDEN_CHANGE_IND(+) IS NULL AND
  -- GOREMAL
  GOREMAL_PIDM(+) = SPRIDEN_PIDM AND
  GOREMAL_EMAL_CODE(+) = 'FSEM' AND
  GOREMAL_STATUS_IND(+) = 'A' AND
  -- STVTERM
  STVTERM_CODE = SSBSECT_TERM_CODE AND
  -- STVCOLL
  STVCOLL_CODE = NVL(SSBOVRR_COLL_CODE, SCBCRSE_COLL_CODE) AND
  -- STVDEPT
  STVDEPT_CODE = NVL(SSBOVRR_DEPT_CODE, SCBCRSE_DEPT_CODE) AND
  -- STVCAMP
  BANNER_CAMP_CODE = SSBSECT_CAMP_CODE
ORDER BY
  "termCode",
  "crn"