WITH
  SCBCRSE AS (
    SELECT
      o.SCBCRSE_SUBJ_CODE,
      o.SCBCRSE_CRSE_NUMB,
      o.SCBCRSE_EFF_TERM,
      o.SCBCRSE_COLL_CODE,
      o.SCBCRSE_DEPT_CODE,
      o.SCBCRSE_TITLE
    FROM
      SCBCRSE@BREPTS o
    WHERE
      o.SCBCRSE_CSTA_CODE = 'A' AND
      o.SCBCRSE_EFF_TERM = (
        SELECT
          MAX(i.SCBCRSE_EFF_TERM)
        FROM
          SCBCRSE@BREPTS i
        WHERE
          i.SCBCRSE_SUBJ_CODE = o.SCBCRSE_SUBJ_CODE AND
          i.SCBCRSE_CRSE_NUMB = o.SCBCRSE_CRSE_NUMB AND
          i.SCBCRSE_EFF_TERM <= :termCode AND
          i.SCBCRSE_CSTA_CODE = 'A'
      )
  ),
  SIRASGN AS (
    SELECT
      SIRASGN_TERM_CODE,
      SIRASGN_CRN,
      SPRIDEN_PIDM,
      SPRIDEN_ID,
      SPRIDEN_FIRST_NAME,
      SPRIDEN_LAST_NAME,
      GOREMAL_EMAIL_ADDRESS
    FROM
      SIRASGN@BREPTS,
      SPRIDEN@BREPTS,
      GOREMAL@BREPTS
    WHERE
      -- SIRASGN
      SIRASGN_TERM_CODE = :termCode AND
      SIRASGN_PRIMARY_IND = 'Y' AND
      -- SPRIDEN
      SPRIDEN_PIDM = SIRASGN_PIDM AND
      SPRIDEN_CHANGE_IND IS NULL AND
      -- GOREMAL
      GOREMAL_PIDM(+) = SPRIDEN_PIDM AND
      GOREMAL_EMAL_CODE(+) = 'FSEM' AND
      GOREMAL_STATUS_IND(+) = 'A'
  ),
  STVCAMP AS (
    SELECT
      STVCAMP_CODE AS BANNER_CAMP_CODE,
      CASE
        WHEN STVCAMP_CODE IN ('PF','ON','OG') THEN 'ON'
        WHEN STVCAMP_CODE IN ('PA','PC','PE','PN','PS') THEN 'PER'
        WHEN STVCAMP_CODE IN ('A','1') THEN 'ATL'
        WHEN STVCAMP_CODE IN ('I') THEN 'FOR'
        WHEN STVCAMP_CODE IN ('X','F','PF') THEN 'OFF'
        ELSE 'OTH'
      END AS STVCAMP_CODE,
      CASE
        WHEN STVCAMP_CODE IN ('PF','ON','OG') THEN 'Online Campus'
        WHEN STVCAMP_CODE IN ('PA','PC','PE','PN','PS') THEN 'Perimeter Campus'
        WHEN STVCAMP_CODE IN ('A','1') THEN 'Atlanta Campus'
        WHEN STVCAMP_CODE IN ('I') THEN 'Foreign Campus'
        WHEN STVCAMP_CODE IN ('X','F','PF') THEN 'Off-campus'
        ELSE 'Other USG Institution'
      END AS STVCAMP_DESC
    FROM
      STVCAMP@BREPTS
  )
SELECT
  STVTERM_CODE AS "termCode",
  STVTERM_DESC as "termName",
  STVCOLL_CODE AS "collegeCode",
  STVCOLL_DESC AS "collegeName",
  STVDEPT_CODE AS "departmentCode",
  STVDEPT_DESC AS "departmentName",
  STVCAMP_CODE AS "campusCode",
  STVCAMP_DESC AS "campusName",
  SCBCRSE_EFF_TERM AS "courseEffectiveTerm",
  SSBSECT_SUBJ_CODE AS "subjectCode",
  SSBSECT_CRSE_NUMB AS "courseNumber",
  SSBSECT_SEQ_NUMB AS "courseSequence",
  SSBSECT_CRN AS "crn",
  SSBSECT_SCHD_CODE AS "scheduleCode",
  NVL(SSBSECT_CRSE_TITLE,SCBCRSE_TITLE) AS "courseTitle",
  NVL(SPRIDEN_PIDM,'0') AS "instructorPidm",
  NVL(SPRIDEN_ID,'STAFF') AS "instructorId",
  SPRIDEN_FIRST_NAME AS "instructorFirstName",
  SPRIDEN_LAST_NAME AS "instructorLastName",
  GOREMAL_EMAIL_ADDRESS AS "instructorEmail"
FROM
  STVTERM@BREPTS,
  SSBSECT@BREPTS,
  SCBCRSE,
  SSBOVRR@BREPTS,
  STVCOLL@BREPTS,
  STVDEPT@BREPTS,
  SIRASGN,
  STVCAMP
WHERE
  STVTERM_CODE = :termCode AND
  -- SSBSECT
  SSBSECT_TERM_CODE = STVTERM_CODE AND
  SSBSECT_SSTS_CODE = 'A' AND
  SSBSECT_INTG_CDE IS NULL AND
  SSBSECT_MAX_ENRL > 0 AND
  -- SCBCRSE
  SCBCRSE_SUBJ_CODE = SSBSECT_SUBJ_CODE AND
  SCBCRSE_CRSE_NUMB = SSBSECT_CRSE_NUMB AND
  -- SSBOVRR
  SSBOVRR_TERM_CODE(+) = SSBSECT_TERM_CODE AND
  SSBOVRR_CRN(+) = SSBSECT_CRN AND
  -- SIRASGN
  SIRASGN_TERM_CODE(+) = SSBSECT_TERM_CODE AND
  SIRASGN_CRN(+) = SSBSECT_CRN AND
  -- STVCOLL
  STVCOLL_CODE = NVL(SSBOVRR_COLL_CODE, SCBCRSE_COLL_CODE) AND
  -- STVDEPT
  STVDEPT_CODE = NVL(SSBOVRR_DEPT_CODE, SCBCRSE_DEPT_CODE) AND
  -- STVCAMP
  BANNER_CAMP_CODE = SSBSECT_CAMP_CODE
ORDER BY
  "termCode",
  "crn"
