SELECT
  STVTERM_CODE AS "termCode",
  STVTERM_DESC as "termName"
FROM
  STVTERM@BIPROD_BREPT_LINK_MFOREST
WHERE
  STVTERM_CODE LIKE '%01' AND
  STVTERM_START_DATE >= SYSDATE - (4 * 7) AND
  STVTERM_START_DATE <= SYSDATE + (11 * 7) + (4 * 7)
UNION
SELECT
  STVTERM_CODE AS "termCode",
  STVTERM_DESC as "termName"
FROM
  STVTERM@BIPROD_BREPT_LINK_MFOREST
WHERE
  STVTERM_CODE LIKE '%05' AND
  STVTERM_START_DATE >= SYSDATE - (4 * 7) AND
  STVTERM_START_DATE <= SYSDATE + (10 * 7) + (4 * 7)
UNION
SELECT
  STVTERM_CODE AS "termCode",
  STVTERM_DESC as "termName"
FROM
  STVTERM@BIPROD_BREPT_LINK_MFOREST
WHERE
  STVTERM_CODE LIKE '%08' AND
  STVTERM_START_DATE >= SYSDATE - (4 * 7) AND
  STVTERM_START_DATE <= SYSDATE + (21 * 7) + (4 * 7)
